# Catppuccin Mocha Theme
include mocha.conf

# Font
font_family JetBrains Mono
font_size 13.0

# Cursor
cursor_shape beam
cursor_blink_interval 0.5

# Window
background_opacity 0.7
window_padding_width 12

# Tab bar
tab_bar_style powerline
tab_powerline_style slanted

# Bell
enable_audio_bell no

#fixing the default editor for config file to be one in write mode
editor nano

#create a shortcut for opening kitty.conf
map f1 launch nano ~/.config/kitty/kitty.conf
map f2 launch nano ~/.config/hypr/hyprland.conf
